### DISCUSSION TITLE
Advice on using dynamic versioning with GitHub Actions

### DISCUSSION THREAD

**Discussion by 03bennej** [mtkennerly/poetry-dynamic-versioning#173] [Q&A] [answered]
Hi there, I'm trying to integrate poetry-dynamic-versioning into my project - I'm finding it works locally but I'm unable to get it working as part of Actions. For example, locally I ran:
```
pipx inject poetry "poetry-dynamic-versioning[plugin]"
poetry dynamic-versioning enable
``` 
, and added 
```
[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
tag-branch = "main"
``` 
to pyproject.toml. To test I set the version=0.0.0 and ran `poetry build`, and saw the correct tag. Now when I try and use this in an action, for example:
```
name: Publish to Test PyPI
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
  
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
  
      - name: Install poetry
        run: |
          pip install poetry
  
      - name: Install dependencies
        run: |
          poetry install
      
      - name: Publish package to TestPyPI
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
          poetry publish -r test-pypi --build
``` 
, I find I'm publishing version 0.0.0. Any ideas how to get this working? I did try adding `poetry self add "poetry-dynamic-versioning[plugin]"` but I got an error at `poetry install`.

Thanks, and apologies for the basic question - I'm new to this!
