### ISSUE TITLE
Configuration of "tool.poetry-dynamic-versioning" breaks poetry source config.

### ISSUE THREAD

**Issue by wonderbeyond** [mtkennerly/poetry-dynamic-versioning#103]
I have two `[[tool.poetry.source]]` sections in my pyproject.toml.

After adding

```toml
[tool.poetry-dynamic-versioning]
enable = true
pattern = 'default-unprefixed'
```

`poetry source show` outputs:

> No sources configured for this project.

--- 

```
$ poetry debug info

Poetry
Version: 1.2.0  # I've also tried 1.2.2
Python:  3.10.6

Virtualenv
Python:         3.10.5
Implementation: CPython
Path:           /home/ubuntu/workspace/skylab/.venv
Executable:     /home/ubuntu/workspace/skylab/.venv/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.10.5
Path:       /home/ubuntu/.pyenv/versions/3.10.5
Executable: /home/ubuntu/.pyenv/versions/3.10.5/bin/python3.10
```
