### ISSUE TITLE
Not incrementing dev1 to dev2

### ISSUE THREAD

**Issue by XavierGeerinck** [mtkennerly/poetry-dynamic-versioning#125]
Hi! Thank you for writing this amazing tool. Sadly enough I am having an issue I seem to be unable to wrap my head around. I am trying to push to `package-dev` where I would love to have the version + `devN` as notation.

However, when building with this plugin I get `0.0.1.dev1+9ed5dc2`. So I reconfigured it as the below

```toml
[tool. Poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
bump = true 
format-jinja = "{% if distance == 0 %}{{ base }}{% else %}{{ base }}.dev{{ distance }}{% endif %}"
```

Which does do the publish, but then `dev1` is stuck on `dev1` and doesn't increment. 

Would anyone know how to get `dev1` to increment as well? (and potentially to include the sha hash to PyPI?)
