### ISSUE TITLE
Support poetry dynamic-versioning disable for e.g. Docker

### ISSUE THREAD

**Issue by heimalne** [mtkennerly/poetry-dynamic-versioning#133]
First of all, many thanks for this convenient plugin!

When using poetry within a monorepo (multiple projects inside a Git repository) we have a `pyproject.toml`:

```toml
[tool.poetry]
name = "projectname"
version = "0.0.0"

[tool.poetry-dynamic-versioning]
enable = true # dynamic-versioning-flag-marker, don't delete
vcs = "git"
```

As soon as we want to "poetry install" a single project inside Docker we don't have access to Git anymore so the versioning plugin fails. Our workaround is to manually modify the `pyproject.toml` by replacing the version with the plugin's computed version and to set "enabled = false". 

```bash
poetry dynamic-versioning # Modify "version = ..."
sed -i 's/.*dynamic-versioning-flag-marker.*/enable=false/' pyproject.toml # Modify "enabled = .."
```

A "poetry dynamic-versioning disable" call would be convenient, or maybe adding that effect to the plain "poetry dynamic-versioning" call (since when the version is set you don't need the section anymore). What do you think?
