### ISSUE TITLE
Building on ci server creates version `0.0.0`

### ISSUE THREAD

**Issue by mrt181** [mtkennerly/poetry-dynamic-versioning#145]
When I build locally the package is created correctly:

```shell
poetry build
Building proto-model (1.2.1+sha.8cda395)
  - Building sdist
  - Built proto_model-1.2.1+sha.8cda395.tar.gz
  - Building wheel
  - Built proto_model-1.2.1+sha.8cda395-py3-none-any.whl
```

When I build on the CI server (azure devops) with this settings

```yaml
  steps:
  - checkout: self
    fetchTags: true
    fetchDepth: 0
  - task: UsePythonVersion@0
    displayName: Set python version
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'
  - task: Bash@3
    displayName: Install poetry
    inputs:
      targetType: 'inline'
      script: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        pipx install poetry
  - task: Bash@3
    displayName: Publish python
    inputs:
      targetType: 'inline'
      script: |
        poetry config repositories.azure $(POETRY_REPOSITORIES_AZURE_URL)
        poetry config http-basic.azure $(POETRY_HTTP_BASIC_AZURE_USERNAME) $(POETRY_HTTP_BASIC_AZURE_PASSWORD)
        poetry install
        poetry build
        poetry publish -r azure
```

I get this instead
```shell
Creating virtualenv proto-model-3AFF4dIC-py3.11 in /home/vsts/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Installing the current project: proto-model (0.0.0)
Building proto-model (0.0.0)
  - Building sdist
  - Built proto_model-0.0.0.tar.gz
  - Building wheel
  - Built proto_model-0.0.0-py3-none-any.whl

Publishing proto-model (0.0.0) to azure
 - Uploading proto_model-0.0.0-py3-none-any.whl 0%
 - Uploading proto_model-0.0.0-py3-none-any.whl 100%
```

Why does it not get the right version in CI?
