### ISSUE TITLE
Using poetry to install dependency with poetry-dynamic-versioning

### ISSUE THREAD

**Issue by rusnyder** [mtkennerly/poetry-dynamic-versioning#154]
First off - incredible project!  Delighted to stumble across it, and a potential godsend for some versioning issues my team has been having.

## Issue
I may just be missing something from the docs, but this plugin works flawlessly in all contexts I need it _except_ when trying to install a project that uses poetry-dynamic-versioning via VCS (`git`).

Using your https://github.com/mtkennerly/playground project (thank you!), `pip install` works as advertised, but `poetry install` is a little wonky

### Pip
```bash
$ python3 -m venv venv
$ . ./venv/bin/activate
$ pip install git+ssh://git@github.com/mtkennerly/playground@master
...
Successfully installed dummy-python-project-0.1.0.post8.dev0+d3a036f
```

### Poetry
**`pyproject.toml`**
```toml
[tool.poetry]
name = "fake-project"
version = "0.1.0"
description = ""
authors = ["Russell Snyder <russ@arceo.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

dummy-python-project = { git = "https://github.com/mtkennerly/playground" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

```bash
# First install shows the `version` from pyproject.toml, not the dynamic version
$ poetry install
Creating virtualenv fake-project-GaTXRtqa-py3.8 in /Users/.../Library/Caches/pypoetry-arm64/virtualenvs
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing dummy-python-project (0.0.999 d3a036f)

# All following installs will "downgrade" to the same version, half-detecting the right version
$ poetry install
Installing dependencies from lock file

Package operations: 0 installs, 1 update, 0 removals

  • Downgrading dummy-python-project (0.1.0.post8.dev0+d3a036f d3a036f -> 0.0.999 d3a036f)

```

This _almost_ works great, and you can tell under the hood the right version is being detected and reported, but it seems like poetry's locking in-particular is failing to register the version.

## Question/Thoughts
Main question: Is this a limitation on the poetry end? It reads like it could be a symptom of the caveat from your README (that a few closed issues also allude to):

> The dynamic version is not available during poetry run or poetry shell because of a [Poetry design choice](https://github.com/python-poetry/poetry/issues/8092) that prevents the plugin from cleaning up after itself.

I'm hoping I'm just being dense and missed something simple.  I may dig into this in a week or so, but figured I'd post the inquiry in case it was something quick!
