### ISSUE TITLE
Create a file with the version in it without any "replacement magic"

### ISSUE THREAD

**Issue by crash5** [mtkennerly/poetry-dynamic-versioning#155]
I would like a simple VERSION file which only contains the version. As I see there is no way for it now without putting some dummy replacement pattern into it?

For now I'm using this codes but it feels over complicated:
```
[tool.poetry-dynamic-versioning.substitution]
patterns = [
    '()0.0.0-non-production-ready()'  # 2 empty capturing group because we don't want to keep anything around the pattern
]
files = [
    '*/VERSION'
]
folders = [
    { path = "src" }
]

[tool.poetry-dynamic-versioning.files.'src/packagename/VERSION']
persistent-substitution = true
initial-content = '0.0.0-non-production-ready'
```

**Comment by mtkennerly** [comment]
Yeah, that's awkward for your use case. I could add an option like this:

```toml
[tool.poetry-dynamic-versioning.files.'src/packagename/VERSION']
initial-content-jinja = "{{ formatted_version }}"
```

...where `{{ formatted_version }}` would map to the output of the `format` or `format-jinja` configuration.
