### ISSUE TITLE
Version not substituted for chained package dependencies

### ISSUE THREAD

**Issue by bergercookie** [mtkennerly/poetry-dynamic-versioning#158]
Hi there and thanks for the great work with this project!

I have the following project structure:

```
.
├── pkg0/
│   ├── pkg0
│   ├── poetry.lock
│   └── pyproject.toml
├── pkg1/
│   ├── pkg1
│   ├── poetry.lock
│   └── pyproject.toml2
└── pkg2
    ├── pkg2/
    ├── poetry.lock
    └── pyproject.toml
 ```
 
 whereas `pkg0` depends on development versions of local `pkg1`, `pkg2` as follows:
 
 ```toml
[tool.poetry]
name = "pkg0"
version = "0.1.0"
description = "pkg1 description"
authors = ["Nikos Koukis <something@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"

pkg2 = { path = "../pkg2", develop = true }
pkg1 = { path = "../pkg1", develop = true }

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
```

`pkg1` requires `pkg2`. Assume that `pkg2` exists on PyPI index and so we just specify its version here:

```toml
[tool.poetry]
name = "pkg1"
version = "0.0.0"
description = "pkg0"
authors = ["Nikos Koukis <something@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
pkg2 = "^0.100.0"

[tool.poetry-dynamic-versioning]
enable = true
metadata = false
dirty = false
style = "pep440"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
```

`pkg2` doesn't specify any dependencies:

```toml
[tool.poetry]
name = "pkg2"
version = "0.0.0"
description = "pkg2 description"
authors = ["Nikos Koukis <something@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"

[tool.poetry-dynamic-versioning]
enable = true
metadata = false
dirty = false
style = "pep440"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
```

Each one of the `pkg{0,1,2}` are inside their own git repos with a few sample commits created. `pkg0` is on `v0.1.0`, `pkg1` is on `v0.10.0` and `pkg2` is on `v0.100.0`

As summing the above setup, when I `cd` into the `pkg0` git repo and issue `poetry install` I get the following:

```
at 22:44:51 ➜ poetry update
Updating dependencies
Resolving dependencies... (0.0s)

Because pkg1 (0.0.0) @ file:///home/main/apkg1 depends on pkg2 (^0.100.0)
 and pkg0 depends on pkg2 (0.0.0) @ file:///home/main/a/pkg2, pkg1 is forbidden.
So, because pkg0 depends on pkg1 (0.0.0) @ file:///home/main/a/pkg1, version solving failed.
```

What's interesting is that If I enable the `poetry-dynamic-versioning` plugin for `pkg0` as well, then this works fine and dependencies are resolved as expected on `poetry update`. I.e., the following snippet in the pyproject.toml of `pkg0` solves it:

```toml
[tool.poetry-dynamic-versioning]
enable = true
metadata = false
dirty = false
style = "pep440"
```

I'm using poetry `1.6.1`.

This isn't a pressing issue for me since making `pkg0` use dynamic versioning is not a problem. It does seem odd to me and I was wondering whether this is a bug and how it occured.
Any pointers?
