### ISSUE TITLE
tool.poetry.version field is not updated

### ISSUE THREAD

**Issue by steven-douilliet** [mtkennerly/poetry-dynamic-versioning#182]
Hello,

When I run the `poetry build` command, the `tool.poetry.version` field is not updated and remains at `0.0.0` (placeholder).
While the source and wheel archives are correctly versioned, as well as `__version __` and `__version_tuple __`.

See below my config:
```toml
[tool.poetry]
...
version = "0.0.0"
...

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format = "{base}"
style = "semver"
latest-tag = true
bump = true

[tool.poetry-dynamic-versioning.files."private/__init__.py"]
persistent-substitution = true
initial-content = """
__version__ = "0.0.0"
__version_tuple__ = (0, 0, 0)


__all__ = (
    "__version__",
    "__version_tuple__",
)
"""

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
```
