### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by itssimon** [mtkennerly/poetry-dynamic-versioning#205]
After adding the `requires-plugin` section to my pyproject.yaml, running `poetry install` fails. Without that section, everything installs fine.

```toml
[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }
```

```shell
❯ poetry install --with dev
Removing the project's plugin cache because it is outdated
Ensuring that the Poetry plugins required by the project are available...
The following Poetry plugins are required by the project but are not installed in Poetry's environment:
  - poetry-dynamic-versioning[plugin] (>=1.0.0,<2.0.0)
Installing Poetry plugins only for the current project...
Updating dependencies
Resolving dependencies... (7.8s)

Because poetry-project-instance depends on gpg (1.24.1) which doesn't match any versions, version solving failed.
```
