### ISSUE TITLE
`version` removed from `[project.dynamic]` if working in PEP 621 mode

### ISSUE THREAD

**Issue by PrieJos** [mtkennerly/poetry-dynamic-versioning#213]
Hello,

We upgraded to poetry version 2.0.0 and adapting the `pyproject.toml` accordingly so that project information is maintained in `[project]` instead of `[tool.poetry]`. Along the way, we also adapted this `pyproject.toml` file as stated in [README.md](https://github.com/mtkennerly/poetry-dynamic-versioning#installation) so that:

- `version` is added to array `project.dynamic`.
- `version` is not present under `[project]`.
- `version` is added and present under `[tool.poetry]`.

Apart from that, `poetry-dynamic-versioning` is also enabled on our configuration as follows:

```toml
[tool.poetry-dynamic-versioning]
enable = true
style = "semver"
vcs = "git"
pattern = "^v?(?P<base>\\d+\\.\\d+\\.\\d+)$"
bump = true
format-jinja = """
{%- if distance == 0 -%}
{{ serialize_semver(base) }}
{%- else -%}
{{ serialize_semver(base, ["dev", distance], [commit]) }}
{%- endif -%}
"""
```

With that, as long as we try to generate another project version using command:

```shell
poetry dynamic-versioning
```

The corresponding files containing `__version__` and the `pyproject.toml` are modified accordingly. However, and this is indeed the issue I am reporting here, `poetry-dynamic-versioning` is not keeping the PEP 621 mode any longer in `pyproject.toml`, meaning the following modifications are introduced after that command execution:

- `version` is removed from `project.dynamic`
- `version` is moved back from `[tool.poetry]` to `[project]`

With that new configuration in `pyproject.toml`, the `poetry dynamic-versioning` command won't work anymore. Well, actually it works but it does nothing.

Is this behavior expected or intentional? I was expecting though `poetry-dynamic-versioning` to keep configuration in `pyproject.toml` the same except the value assigned to `tool.poetry.version`.

Thanks in advanced for your support.

Cheers
Jose M. Prieto
