### ISSUE TITLE
pip wheel alternative

### ISSUE THREAD

**Issue by fredrikaverpil** [mtkennerly/poetry-dynamic-versioning#23]
I have a bit of a problem with this issue in production. We use git links in pyproject.toml:

```
[tool.poetry.dependencies]
pkg1 = { git = "ssh://SERVER/repo" }
```

The version in pyproject is untouched, and left at 0.0.0, since we apply versioning using your plugin instead.
I then need to deliver wheels to an air-gapped system and so I need to perform something like:

```bash
$ poetry export -f requirements.txt --output requirements.txt
$ pip wheel -r requirements.txt  # downloads all wheels for delivery
```

The resulting requirements.txt file:
```
-e git+ssh://SERVER/repo.git@<hash>#egg=pc-sw
```

The resulting downloaded wheel is named `pkg1-0.0.0-py3-none-any.whl` but I was actually expecting a proper semver version here, not 0.0.0. 😢 

I presume the problem here is that the wheel is built through pip (where your plugin is not available). I wonder if I could somehow instead use poetry so to get the actual SCM-managed version used as the version of the wheel, instead of "0.0.0" Any ideas?

**Comment by mtkennerly** [comment]
A couple of questions:

* Does pkg1's pyproject.toml contain the `build-system` section?
  ```toml
  [build-system]
  requires = ["poetry>=1.0.0"]
  build-backend = "poetry.masonry.api"
  ```
* Does passing `--use-pep517` help?

I have a test for `pip wheel --use-pep517 .` to build a specific, single project, but I haven't tried it by going through a requirements.txt file. I would have expected it to work the same both ways, though.

**Comment by fredrikaverpil** [comment]
Actually, I have this in the pk1's pyproject.toml, so it's not the entire poetry package:

```toml
[build-system]
requires = ["poetry-core>=1.0.0a9"]
build-backend = "poetry.core.masonry.api"
```

Passing `--use-pep517` does not help:

```bash
poetry export --without-hashes -f requirements.txt > requirements.txt
pip wheel -r requirements.txt --use-pep517
```

I still get the `pkg1-0.0.0-py3-none-any.whl` built.

**Comment by mtkennerly** [comment]
@fredrikaverpil This is now fixed in [v0.9.0 of the plugin](https://github.com/mtkennerly/poetry-dynamic-versioning/releases/tag/v0.9.0). Could you try it out and let me know if you still see any issues with this?

I added a bit of info to the README about how the plugin interacts with Pip's PEP 517 mode. Copying it here for reference:

> `pip wheel .` will not work, because Pip creates an isolated copy of the source code, which does not contain the Git history and therefore cannot determine the dynamic version.
>
> If you want to build wheels of your dependencies, you **can** do the following, but it won't work with path dependencies for the same reason as above:
>
>  ```
> poetry export -f requirements.txt -o requirements.txt --without-hashes
> pip wheel -r requirements.txt
> ```

Since you're using Git dependencies, you shouldn't hit those issues (at least based on the testing I did).

**Comment by fredrikaverpil** [comment]
Oh, awesome!
I'll try this out now.

>Edit: Also, either you'll need to add the plugin to the build-system section or you'll need to pass --no-build-isolation. Otherwise, Pip's isolated build environment won't have access to the plugin.

Okay, you mean like this in the pyproject.toml, right?

```
[build-system]
requires = ["poetry-core>=1.0.0a9", "poetry-dynamic-versioning>=0.9.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by mtkennerly** [comment]
Yep, that's what I meant.

**Comment by fredrikaverpil** [comment]
I am not sure what I am doing wrong, but on my end I still end up with a 0.0.0 version wheel:

Did you try this with poetry 1.0.x or a 1.1 pre-relase?

**Comment by mtkennerly** [comment]
I've been testing with 1.0.10. Is the plugin in the `build-system` of *each* package you're building that needs a dynamic version? Each dependency (that isn't already available as a wheel) ends up in an isolated folder during `pip wheel`, so each one separately needs to know if it's supposed to use the plugin when building (unless you turn off build isolation so that they can see the globally installed plugin).

**Comment by fredrikaverpil** [comment]
I might have made the mistake that in each package, I am using poetry 1.0.10 but I have this in my pyproject.toml files:

```
[build-system]
requires = ["poetry-core>=1.0.0a9", "poetry-dynamic-versioning>=0.9.0"]
build-backend = "poetry.core.masonry.api"
```

I guess I need to instead follow the instructions [here](https://python-poetry.org/docs/faq/#is-tox-supported) and not use the upcoming poetry 1.1 setup (which is poetry-core, poetry.core.masonry.api).

What was your setup like?
Poetry 1.0.10 and the [current instructions](https://python-poetry.org/docs/faq/#is-tox-supported)?

**Comment by mtkennerly** [comment]
Using Poetry 1.0.10, I put the following in this repo's `tests/project/pyproject.toml`:

```toml
[tool.poetry]
name = "project"
version = "0.0.999"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.7"
handshake-client = {git = "git@github.com:naoki-maeda/handshake-client-py.git"}

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Since I didn't have any personal projects using the plugin, I just found one on GitHub. Here are the relevant excerpts from handshake-client-py's pyproject.toml:

```toml
[tool.poetry]
version = "0.0.0" # using poetry-dynamic-versioning

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Then I ran:

```
poetry update
poetry export -f requirements.txt -o requirements.txt --without-hashes
pip wheel -r requirements.txt
```

That produces handshake_client-0.0.0-py3-none-any.whl, since the plugin isn't in the build-system. But if I run:

```
pip wheel -r requirements.txt --no-build-isolation
```

Then it produces handshake_client-0.1.7-py3-none-any.whl (when I have the plugin installed globally).

**Comment by mtkennerly** [comment]
I think the behavior you're seeing with `poetry-core` as the build system makes sense because the plugin currently only knows how to patch `poetry` - specifically `poetry.factory` and `poetry.console.commands.run`. I'll need to add some additional patching to handle `poetry-core` being used as the build system on its own.

**Comment by fredrikaverpil** [comment]
Ah, that explains it.

So I tried to use the following, but that tripped up tox (where I use `isolated_build = true`):

```toml
[build-system]
requires = ["poetry>=0.12", "poetry-dynamic-versioning>=0.9.0"]
build-backend = "poetry.masonry.api"
```

Whenever tox started building the sdist of the project, it crashed.

After instead having resorted to almost the same setup as you have, I can finally make it work with git URLs! ❤🤘

```toml
[build-system]
requires = ["poetry==1.0.10"]
build-backend = "poetry.masonry.api"
```
