### ISSUE TITLE
poetry install & build fails when used with poetry-dynamic-versioning and behind the firewall due to it attempting to access pypi.org

### ISSUE THREAD

**Issue by alexshagiev** [mtkennerly/poetry-dynamic-versioning#231]
pyproject.toml
```toml
[build-system]
requires = [
   "poetry-core>=2.0.0,<3.0.0",
   "poetry-dynamic-versioning">=1.0.0,<2.0.0",
]
build-backend = "poetry_dynamic_versioning.backend"
....
[tool.poetry]
version = "0.0.0"


[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version =">=1.0.0,<2.0.0", extras = ["plugin"] )
... 
[[tool.poetry.source]]
name=local
url="https://internal/simple"
priority="primary"
[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

```

```sh
micromamba create   --name=blah   python=3.12
micromamba run        --name=blah   pip install "poetry>=2"
micromamba run        --name=blah   poetry install --verbose # fails 
```

```
using virtualenv: ~/.loca/share/mamba/envs/blah
checking keyring availability: unavailable 
Ensuring that ....
the following poetry plugins are requires and not installed ...
  - poetry-dynamic-versioning[plugins] (.....)
  - version (==0.0.0)
  - Installing poetry plugin only for current project ....
  -Path /home/conda/feeedstock_root/build_artifacts/pip_x/work for pip does not exist
Updating deps...
resolving dips...


Value Error

 Path /home/conda/feeedstock_root/build_artifacts/pip_x/work for pip does not existh 
 
at ~/.local/share/mamba/envs/blah/lib/....../site-packages/poetry/core/packages/path_dependency.py:82 in validate
```
