### ISSUE TITLE
Invalid Version after Pre-release is bumped

### ISSUE THREAD

**Issue by RafaelWO** [mtkennerly/poetry-dynamic-versioning#232]
Hello,

I have been using poetry-dynamic-versioning for quite a while now and it's a great tool!

However, I now get an error stating `Invalid PEP 440 version` after running poetry on a commit ahead of a pre-release tag. Here is my git log:

```
$ git log --oneline 
7e1eabc (HEAD -> change/my-change, origin/change/my-change) 🚧 WIP: Refactor
cdbaabc (tag: 2.12.0-pre.1, origin/main, origin/HEAD, main) Merge branch 'change/update-from-template' into 'main'
```

I created a tag on the main branch with the value `2.12.0-pre.1` to get a pre-release built. Now I am continuing to work (in a separate branch, 1 commit ahead) and get the following error when running `poetry version`

```
Invalid PEP 440 version: '2.12.0-pre.2.pre.1+7e1eabc'
```

What is the correct way of dealing with bumps after a pre-release tag using the semver style?

My config for poetry-dynamic-versioning:

```toml
[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
pattern = "default-unprefixed"
dirty = true
bump = true
```

P.S. If I use `style = "pep440"`, I get a valid version: `2.12.0rc2.dev1+7e1ebb2.dirty`
