### ISSUE TITLE
Github actions error to publishing

### ISSUE THREAD

**Issue by marcuxyz** [mtkennerly/poetry-dynamic-versioning#27]
Hi,
thanks a lot for create project.

I have a issue https://github.com/scanapi/scanapi/runs/1225685171?check_suite_focus=true

every time I try to generate a new tag before sending it to pypi. it returns a 0.0.0 tag
He cannot identify the project's tags. Was there a way to solve this?

**Comment by mtkennerly** [comment]
By default, `actions/checkout` only fetches a single commit, which means the full tag history is unavailable. You just need to set the `fetch-depth`:

```yaml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```
