### ISSUE TITLE
First `poetry install` does not include dynamic version

### ISSUE THREAD

**Issue by uSpike** [mtkennerly/poetry-dynamic-versioning#47]
Using `Poetry` version 1.1.5, `poetry-dynamic-versioning` 0.12.6, my `pyproject.toml` contains:
```toml
[tool.poetry]
name = "mylib"
version = "0"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format = "0.1.2+{commit}"

[tool.poetry.dependencies]
poetry-dynamic-versioning = "^0.12.6"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=0.12.6"]
build-backend = "poetry.core.masonry.api"
```

When I first clone my repository and `poetry install`, the installed version of `mylib` is `0`.  

```
Installing the current project: mylib (0)
```
If I run `poetry install` again, then the version is correctly set to `0.1.2+<hash>`.

```
No dependencies to install or update                                                                                                      
                                                                                                                                          
Installing the current project: mylib (0.1.2+b0703a2)     
```
