### ISSUE TITLE
Query the current version from python REPL?

### ISSUE THREAD

**Issue by fredrikaverpil** [mtkennerly/poetry-dynamic-versioning#53]
Hi,

I've got the following in my `pyproject.toml`:

```toml
[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern  = "^(?P<base>\\d+\\.\\d+\\.\\d+)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?"
format-jinja = """
    {%- if distance == 0 -%}
        {{- base -}}
    {%- else -%}
        {{- bump_version(base, 2) }}.dev{{ distance }}+g{{ commit }}.d{{ datetime.now().strftime('%Y%m%d%H%M%S') -}}
    {%- endif -%}
"""
format-jinja-imports = [
    { module = "datetime", item = "datetime" }
]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
```

How can I, using only the REPL (and of course with poetry-dynamic-versioning installed in my venv) query for the current version in my git project?
