### ISSUE TITLE
[Question] Using with github actions

### ISSUE THREAD

**Issue by galleon** [mtkennerly/poetry-dynamic-versioning#55]
Hi

First, a big thank for your work and the package.
I am looking at using `poetry-dynamic-versioning` from an existing gh workflow. To give you a bit of context I am looking at building daily snaphots on top of regular tagged releases that are deployed on PyPi.

My Python/C++ project is using `poetry` but I am using `build` to run my workflows on GH. Cloning my repo on my laptop, and running `poetry build` locally seems to be running ok generating an artifact (`scikit_decide-0.9.1.post81.dev0+f02af31-cp38-cp38-macosx_10_15_x86_64.whl`)

Launching my workflow on GH leads to a very different result. The generated artifact is now: `scikit_decide-0.0.0.post1.dev0+f02af31-cp38-cp38-macosx_10_15_x86_64.whl`

Can this be due to the way I clone my repo ?

```
      - name: Checkout scikit-decide source code
        uses: actions/checkout@v2
        with:
          submodules: true
```

while my build is done using:

```
      - name: Build macOS/Windows wheel
        if: matrix.os != 'ubuntu-latest'
        run: |
          python -m pip install --upgrade -q pip
          pip install build poetry-dynamic-versioning
          python -m build --sdist --wheel
```

Thanks

**Comment by mtkennerly** [comment]
Hi! GitHub workflows only do a shallow clone by default, so it won't automatically know about the tags. Try setting `fetch-depth: 0` when you clone it:

```
      - name: Checkout scikit-decide source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
```

If that still doesn't work, then add `dunamai from git --debug` to the workflow (after installing the plugin) to rule out whether it could be an issue with using `build`.
