### ISSUE TITLE
[Question] Datetime based versioning

### ISSUE THREAD

**Issue by RoelantStegmann** [mtkennerly/poetry-dynamic-versioning#70]
Hi!

We were always packaging using a datetime pattern, for internal company packages. This is very convenient when you pin the versions as we do for production systems (we don't want updates to break our systems), as it also shows the user when the version it depends on was created. 

I tried a few things but I'm not fully understanding how I could implement such a pattern with this tool. Is it possible? 

```
version = datetime.datetime.now().strftime("%Y.%m.%d.%H%M")
```

**Comment by mtkennerly** [comment]
You can do this by using the Jinja formatting options:

```toml
format-jinja = "{{ datetime.datetime.now().strftime('%Y.%m.%d.%H%M') }}"
format-jinja-imports = [
    { module = "datetime" }
]
```

That will do it for both internal and public versions, so you would probably want to add some logic based on `if distance > 0`.
