### ISSUE TITLE
Dynamic Versioning is not taking the tag in GitHub Actions

### ISSUE THREAD

**Issue by estyxx** [mtkennerly/poetry-dynamic-versioning#78]
Hi

This is an amazing project and I would like to integrate in my little package, everything is working fine locally but when I run with GitHub actions it is taking the placeholder version `0.0.0`... 
I don't understand what I'm doing wrong... :( 

this is the pyproject.toml
```toml
[tool.poetry]
name = "oktagon-python"
version = "0.0.0" # placeholder
...
[tool.poetry.dependencies]
...
poetry-dynamic-versioning = "^0.17.0" # <- also added here... 


...

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

```

The ci: 
```yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  ...

  test-publish:
    name: Publish on test PyPI
    runs-on: ubuntu-latest
    needs: tests
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: ✨ Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.11"

      - name: 🐍 Install dependencies
        run: |
          pip install poetry-dynamic-versioning
          poetry install
        
      - name: 📦 Build package
        run: poetry build

      - name: Metadata
        id: metadata
        run: |
          echo '::echo::on'
          set +e
          echo $(poetry run dunamai from git --no-metadata --style semver)
          echo "::set-output name=commit::$(make hash)"

      - name: Publish release version on Test PyPI
        id: release
        env:
          OKTAGON_TEST_PYPI_TOKEN: ${{ secrets.OKTAGON_TEST_PYPI_TOKEN }}
        run: |
          echo '::echo::on'
          set +e
          make pre-release
          make build
          make publish-test
      
      - name: Create
        uses: peter-evans/create-or-update-comment@v1
        if: steps.check_release.outputs.release == ''
        with:
          issue-number: ${{ github.event.number }}
          body: |
            # Pre-release
            :wave:
            Pre-release **${{ steps.release.outputs.version }}** [${{ steps.metadata.outputs.commit }}] has been released on Test PyPi! :rocket:
            You can try it by doing:
            ```shell
            pip install --extra-index-url https://test.pypi.org/simple/ oktagon-python==${{ steps.release.outputs.version }}
            ```

```

but it will build the package with 0.0.0: 
```log
 poetry version 0.0.0-post.1+85f8701.dev.1652785204
Bumping version from 0.0.0-post.1+85f8701 to 0.0.0-post.1+85f8701.dev.1652785204
poetry build
Building oktagon-python (0.0.0-post.1+85f8701)
  - Building sdist
  - Built oktagon-python-0.0.0.post1+85f8701.tar.gz
  - Building wheel
  - Built oktagon_python-0.0.0.post1+85f8701-py3-none-any.whl
```

Can you help me understand why is not taking correctly the version from the tag that is `0.0.16` atm?

**Comment by mtkennerly** [comment]
Hi! By default, the workflow only downloads the latest commit without the rest of the history. That also means it won't know about any tags, unless the latest commit has one.

You can fix this by setting the following option:

```yaml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
```
