### ISSUE TITLE
`poetry lock` fails after "poetry-dynamic-versioning" installation

### ISSUE THREAD

**Issue by AIGeneratedUsername** [mtkennerly/poetry-dynamic-versioning#92]
### Versions:
- Poetry 1.2.1
- Python 3.10
- Lubuntu 22.04

### pyproject.toml
```toml
[tool.poetry]
# my details are omitted for readability

[tool.poetry.dependencies]
# my dependencies are omitted for readability


[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
```

### `poetry lock` result
```
Pattern '(?x)                                                        (?# ignore whitespace)
    ^v((?P<epoch>\d+)!)?(?P<base>\d+(\.\d+)*)                   (?# v1.2.3 or v1!2000.1.2)
    ([-._]?((?P<stage>[a-zA-Z]+)[-._]?(?P<revision>\d+)?))?     (?# b0)
    (\+(?P<tagged_metadata>.+))?$                               (?# +linux)' did not match any tags from ['0.1.1']
```

### Workaround
After removing 
```toml
[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
```
`poetry lock` works again.
