### ISSUE TITLE
Using the plugin from GitHub Actions

### ISSUE THREAD

**Issue by mavam** [mtkennerly/poetry-dynamic-versioning#94]
I'm trying to use the plugin from GitHub Actions but the version always comes down to `0.0.0.post1.dev0+5270cf1`. In my local environment, the version gets correctly displayed as `2.3.0-post.420+9839bde65`. Any ideas what's going on? Interestingly, `5270cf1` is not a valid commit SHA.

My job currently looks like this:

```yaml
      - name: Run poetry install
        working-directory: python
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --all-extras
      - name: Run unit tests
        working-directory: python
        run: poetry run pytest
      - name: Package and publish to Test PyPI
        working-directory: python
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi "${{ secrets.TEST_PYPI_TOKEN }}"
          poetry publish --build -r test-pypi
```

Complete example: https://github.com/tenzir/vast/pull/2607
