### ISSUE TITLE
poetry build does not yield the desired version

### ISSUE THREAD

**Issue by copperwire** [mtkennerly/poetry-dynamic-versioning#99]
Hi,

I've tried to set up a MRE to test dynamic versioning, and cannot reproduce the desired behaviour where `poertry build` should substitute the `0.0.0` version identifier.

Given a project layout :
```
.
├── poetry.lock
├── pyproject.toml
└── src
    └── __init__.py
```

with `pyproject.toml`:
```toml

[tool.poetry]
name = "copperwire"
version = "0.0.0"
description = ""
authors = ["fooBar <foo@bar.com>"]
packages = [
    { include="src", from="." },
]

[tool.poetry-dynamic-versioning]
enabe = true
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]
folders = [
  { path = "src"}
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "*"

[tool.poetry.dev-dependencies]
black = "*"

[build-system]
requires = ["poetry-core>=1.3.0", "poetry-dynamic-versioning"]
build-backend = ["poetry_dynamic_versioning.backend"]

```

a simple substitution target in `__init__.py` as well: 

```
__version__ = "0.0.0"
```

and  a git repository initialized, commited and with a `tag` :

```bash
$ git tag
v0.1.0
```

I would expect the `poetry build` command to build `0.1.0`, but the actual resulting build is `0.0.0`.
Am I simply misunderstanding the use, or setup? 

Poetry is updated as well:
```bash
$poetry --version
Poetry (version 1.2.2)
```

**Comment by mtkennerly** [comment]
Hi! You have a small typo:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 1981870..ecb4982 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -8,7 +8,7 @@ packages = [
 ]

 [tool.poetry-dynamic-versioning]
-enabe = true
+enable = true
 vcs = "git"
 style = "semver"
```

**Comment by copperwire** [comment]
Ah, embarassing. Thanks for pointing it out. 

I still can't get the desired behaviour from `poetry build` after correcting and commiting the typo, though. 
```bash
$ poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: copperwire (0.0.0)
$ poetry build
Building copperwire (0.0.0)
  - Building sdist
  - Built copperwire-0.0.0.tar.gz
  - Building wheel
  - Built copperwire-0.0.0-py3-none-any.whl
```


Current `pyproject.toml`

```toml
[tool.poetry]
name = "copperwire"
version = "0.0.0"
description = ""
authors = ["Robert Solli <robert.solli@statnett.no>"]
packages = [
    { include="src", from="." },
]

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]
folders = [
  { path = "src"}
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "*"

[tool.poetry.dev-dependencies]
black = "*"


[[tool.poetry.source]]
name = "frida-artifactory"
url = "https://artifactory.statnett.no/artifactory/api/pypi/frida-pypi-local/simple/"

[[tool.poetry.source]]
name = "pypi-simple-artifactory"
url = "https://artifactory.statnett.no/artifactory/api/pypi/pypi_statnett_ia_virtual/simple/"
default = true


[build-system]
requires = ["poetry-core>=1.3.0", "poetry-dynamic-versioning"]
build-backend = ["poetry_dynamic_versioning.backend"]
```

**Comment by copperwire** [comment]
*edited to avoid doxxing myself

Ah, embarassing. Thanks for pointing it out. 

I still can't get the desired behaviour from `poetry build` after correcting and commiting the typo, though. 
```bash
$ poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: copperwire (0.0.0)
$ poetry build
Building copperwire (0.0.0)
  - Building sdist
  - Built copperwire-0.0.0.tar.gz
  - Building wheel
  - Built copperwire-0.0.0-py3-none-any.whl
```


Current `pyproject.toml`

```toml
[tool.poetry]
name = "copperwire"
version = "0.0.0"
description = ""
authors = ["fooBar <foo@bar.com>"]
packages = [
    { include="src", from="." },
]

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]
folders = [
  { path = "src"}
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "*"

[tool.poetry.dev-dependencies]
black = "*"


[[tool.poetry.source]]
name = "frida-artifactory"
url = "https://artifactory.statnett.no/artifactory/api/pypi/frida-pypi-local/simple/"

[[tool.poetry.source]]
name = "pypi-simple-artifactory"
url = "https://artifactory.statnett.no/artifactory/api/pypi/pypi_statnett_ia_virtual/simple/"
default = true


[build-system]
requires = ["poetry-core>=1.3.0", "poetry-dynamic-versioning"]
build-backend = ["poetry_dynamic_versioning.backend"]
```
